openapi: 3.0.0
info:
  title: Book Store
  description: A simple web service to keep track of the books in the store.
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: my local dev server
paths:
  /books:

    